apiVersion: v1
kind: Namespace
metadata:
  name: system-education

---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: system-education
  namespace: argocd
spec:
  description: Projeto para os apps do sistema educacional
  sourceRepos:
    - https://github.com/williamkoller/system-education
  destinations:
    - namespace: system-education
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

---
apiVersion: v1
kind: Secret
metadata:
  name: williamkoller-git
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  url: "https://github.com/williamkoller/system-education"
