apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-education
  labels:
    app: system-education
spec:
  replicas: 1
  selector:
    matchLabels:
      app: system-education
  template:
    metadata:
      labels:
        app: system-education
    spec:
      containers:
        - name: system-education
          image: system-education:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: system-education-config
            - secretRef:
                name: system-education-secret
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
