apiVersion: v1
kind: Service
metadata:
  name: system-education
  labels:
    app: system-education
spec:
  selector:
    app: system-education
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
