apiVersion: v1
kind: Secret
metadata:
  name: {{ include "system-education.fullname" . }}-secret
  labels:
    {{- include "system-education.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
